### ISSUE TITLE
LCD pins

### ISSUE THREAD

**Issue by sindigo** [iGEM-Aachen/Open-Source-Peristaltic-Pump#1]
Thank you for sharing your wonderful project! I found one small problem in your code.

**if one build the circuit according to your diagram in the Instructables page.**

in line 18,

> LiquidCrystal lcd(LCD_PIN_RS, LCD_PIN_EN, LCD_PIN_1, LCD_PIN_2, LCD_PIN_3, LCD_PIN_4);

should be 

> LiquidCrystal lcd(LCD_PIN_RS, LCD_PIN_EN, LCD_PIN_4, LCD_PIN_3, LCD_PIN_2, LCD_PIN_1);

**Comment by iGEM-Aachen-User** [comment]
Oh, that's right. Hints like yours are exactly what we were hoping for when we've published our instructions here. Thank you!

We have changed the diagram on instructables to fix the error. The code and the wiring diagram should match now. We also changed the names for the LCD pin constants (D4-D7, instead of 1-4), so that it is the same labeling as on the datasheet of the LCD.

**Comment by sindigo** [comment]
Thanks. Keep up the good work :)
